# Generated by Django 3.2.18 on 2023-06-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0001_add_author_to_Reply_and_o2o_for_previous'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created']},
        ),
    ]
