# Generated by Django 3.2.18 on 2023-06-16 07:29

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0002_add_OpenAiProfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiprofile',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
