version: '3'

services:

  db:
    container_name: postgres
    image: postgres:13.2-alpine
    command: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped

  app:
    build: .
    container_name: backend
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db/${POSTGRES_DB:-postgres}
      - SECRET_KEY=${SECRET_KEY}
      - OPENAI_TOKEN=${OPENAI_TOKEN}
    command: >
      sh -c "./manage.py migrate &&
             ./manage.py runserver"
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./src:/src
    restart: unless-stopped

volumes:
  postgres_data: