version: '3'

services:

  nginx:
    container_name: nginx
    image: ghcr.io/da-maltsev/nginx-gpt-dev:latest
    ports:
      - 80:80
    restart: always


  db:
    container_name: postgres
    image: postgres:13.2-alpine
    command: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped

  app:
    build: .
    container_name: backend
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db/${POSTGRES_DB:-postgres}
      - SECRET_KEY=${SECRET_KEY}
      - SOCIAL_AUTH_VK_OAUTH2_KEY=${VK_OAUTH2_KEY}
      - SOCIAL_AUTH_VK_OAUTH2_SECRET=${VK_OAUTH2_SECRET}
    command: >
      sh -c "./manage.py migrate &&
             ./manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - nginx
    volumes:
      - ./backend:/backend
    restart: unless-stopped

  web:
    build:
      context: ./frontend
    container_name: frontend
    environment:
      - VITE_VK_CLIENT_ID=${VK_OAUTH2_KEY}
      - VITE_VK_SECRET=${VK_OAUTH2_SECRET}
      - VITE_HOST=${HOST}
    command: >
      sh -c "npm run dev"
    depends_on:
      - db
      - nginx
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules/
    restart: unless-stopped

volumes:
  postgres_data: