# Generated by Django 4.1.9 on 2023-06-18 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gpt", "0003_unique_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reply",
            options={"ordering": ["-created"], "verbose_name_plural": "replies"},
        ),
    ]
