---
name: Regular redeploy
on:
  schedule:
    - cron: "*/60 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Read image identifiers
        id: image
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - name: Update image
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            cd gpt
            git pull
            docker compose pull
            echo "${{ secrets.ENV_FILE }}" > .env
            docker compose up -d
            docker image prune -a