---
name: Regular redeploy
on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Read image identifiers
        id: image
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - name: Update image
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            docker rm $(docker ps -a | grep '${{ steps.image.outputs.lowercase }}' | awk '{print $1}')
            docker rmi $(docker images | grep '${{ steps.image.outputs.lowercase }}')
            docker pull ghcr.io/${{ steps.image.outputs.lowercase }}:latest
            docker run -d -e OPENAI_TOKEN=${{ secrets.OPENAI_TOKEN }} -e SECRET_KEY=${{ secrets.SECRET_KEY }} ghcr.io/${{ steps.image.outputs.lowercase }}